# Name of your application. Used to uniquely configure containers.
service: pza-main

# Name of the container image.
image: regedarek/pza-main

# Deploy to these servers.
servers:
  web:
    hosts:
      - 146.59.94.122
    labels:
      traefik.http.routers.blog.entrypoints: websecure
      traefik.http.routers.blog.rule: Host(`pza.kw.krakow.pl`)
      traefik.http.routers.blog.tls.certresolver: letsencrypt

registry:
  username: regedarek
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 146.59.94.122
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

builder:
  args:
    RUBY_VERSION: 3.2.2

accessories:
  db:
    image: postgres:15
    host: 146.59.94.122
    port: 5432
    env:
      clear:
        POSTGRES_USER: "pza"
        POSTGRES_DB: "pza_main_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "dariusz.finster@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json" # Must match the path in `volume`
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web # Must match the role in `servers`
