# Name of your application. Used to uniquely configure containers.
service: pza-main

# Name of the container image.
image: regedarek/pza-main

# Deploy to these servers.
servers:
  web:
    hosts:
      - 146.59.94.122

registry:
  username: regedarek
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 146.59.94.122
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

builder:
  args:
    RUBY_VERSION: 3.2.2

accessories:
  db:
    image: postgres:15
    host: 146.59.94.122
    port: 5432
    env:
      clear:
        POSTGRES_USER: "pza"
        POSTGRES_DB: "pza_main_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
