local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

ovh:
  service: S3
  access_key_id: <%= ENV["S3_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["S3_SECRET_KEY"] %>
  region: waw
  endpoint: "https://s3.waw.io.cloud.ovh.net/"
  bucket: pza-main-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
